# =========================================================
# Project Name : Intelligent Document Question Answering System
#                using RAG and Large Language Models
#
# Author       : Ankita Dnyanoba Shinde
# Date         : 09/05/2026
#
# Description  :
# This project allows the user to upload a PDF document and ask
# questions based on its content. The system uses RAG architecture,
# FAISS vector database, Sentence Transformers embeddings, and a
# local LLM through Ollama to generate context-aware answers.
#
# =========================================================

import streamlit as st
import PyPDF2
import faiss
import numpy as np
import requests

from sentence_transformers import SentenceTransformer

# =========================================================
# Function Name : extract_text_from_pdf
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Extracts readable text from uploaded PDF file.
# Input         : Uploaded PDF file object
# Output        : Extracted text as string
# =========================================================

def extract_text_from_pdf(pdf_file):
    text = ""

    try:
        pdf_reader = PyPDF2.PdfReader(pdf_file)

        for page_number, page in enumerate(pdf_reader.pages):
            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

    except Exception as e:
        st.error(f"Error while reading PDF: {e}")

    return text

# =========================================================
# Function Name : split_text_into_chunks
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Splits large PDF text into smaller overlapping chunks.
# Input         : Text, chunk size, overlap size
# Output        : List of text chunks
# =========================================================

def split_text_into_chunks(text, chunk_size=500, overlap=100):
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]

        if chunk.strip():
            chunks.append(chunk)

        start = end - overlap

    return chunks

# =========================================================
# Function Name : load_embedding_model
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Loads Sentence Transformer model only once.
# Input         : None
# Output        : SentenceTransformer model object
# =========================================================

@st.cache_resource
def load_embedding_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

# =========================================================
# Function Name : create_vector_database
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Converts chunks into embeddings and stores them in FAISS.
# Input         : Text chunks and embedding model
# Output        : FAISS index and embeddings
# =========================================================

def create_vector_database(chunks, embedding_model):
    embeddings = embedding_model.encode(chunks)

    embeddings = np.array(embeddings).astype("float32")

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatL2(dimension)

    index.add(embeddings)

    return index, embeddings


# =========================================================
# Function Name : search_relevant_chunks
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Retrieves top matching PDF chunks for user question.
# Input         : Question, chunks, FAISS index, embedding model, top_k
# Output        : List of relevant chunks
# =========================================================

def search_relevant_chunks(question, chunks, index, embedding_model, top_k=3):
    question_embedding = embedding_model.encode([question])

    question_embedding = np.array(question_embedding).astype("float32")

    distances, indices = index.search(question_embedding, top_k)

    relevant_chunks = []

    for i in indices[0]:
        if i < len(chunks):
            relevant_chunks.append(chunks[i])

    return relevant_chunks


# =========================================================
# Function Name : ask_llm
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Sends context and question to local LLM using Ollama.
# Input         : User question and retrieved context
# Output        : Answer generated by LLM
# =========================================================

def ask_llm(question, context):
    prompt = f"""
You are an intelligent document question answering assistant.

Project:
Intelligent Document Question Answering System using RAG and Large Language Models.

Instructions:
1. Answer only from the given context.
2. Do not use outside knowledge.
3. If the answer is not present in the context, say:
   "I could not find the answer in the uploaded PDF."
4. Give clear and simple explanation.
5. If required, answer in bullet points.

Context:
{context}

Question:
{question}

Answer:
"""

    url = "http://localhost:11434/api/generate"

    payload = {
        "model": "llama3",
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()

        result = response.json()

        return result["response"]

    except requests.exceptions.ConnectionError:
        return "Ollama is not running. Please start Ollama and run: ollama run llama3"

    except Exception as e:
        return f"Error while communicating with LLM: {e}"


# =========================================================
# Function Name : show_project_flow
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# Description   : Displays RAG project flow on Streamlit UI.
# Input         : None
# Output        : None
# =========================================================

def show_project_flow():
    st.markdown("""
    ### Complete Project Flow

    ```text
    PDF Upload
        ↓
    Extract Text from PDF
        ↓
    Split Text into Chunks
        ↓
    Convert Chunks into Embeddings
        ↓
    Store Embeddings in FAISS Vector Database
        ↓
    User Asks Question
        ↓
    Convert Question into Embedding
        ↓
    Search Similar Chunks
        ↓
    Prepare Context
        ↓
    Send Context + Question to LLM
        ↓
    Generate Final Answer
    ```
    """)


# =========================================================
# Streamlit Web Application
# Author        : Ankita Dnyanoba Shinde
# Date          : 09/05/2026
# =========================================================

st.set_page_config(
    page_title="Intelligent Document QA System",
    page_icon="📘",
    layout="wide"
)


# ------------------ Custom Branding CSS ------------------

st.markdown("""
<style>

/* Main Background */

.stApp {
    background: linear-gradient(to right, #0f172a, #1e293b);
    color: white;
}


/* Main Title */

.main-title {
    font-size: 42px;
    font-weight: bold;
    color: #38bdf8;
    text-align: center;
    text-shadow: 2px 2px 5px black;
    margin-top: 10px;
}


/* Project Subtitle */

.sub-title {
    font-size: 24px;
    font-weight: bold;
    color: #facc15;
    text-align: center;
    margin-bottom: 20px;
}


/* Branding Information Box */

.brand-box {
    background: linear-gradient(to right, #1e3a8a, #2563eb);
    color: white;
    border-left: 8px solid #facc15;
    padding: 20px;
    border-radius: 15px;
    margin-bottom: 20px;
    box-shadow: 0px 0px 15px rgba(0,0,0,0.4);
    font-size: 17px;
}


/* Sidebar */

section[data-testid="stSidebar"] {
    background-color: #111827;
    color: white;
}


/* Headers */

h1, h2, h3 {
    color: #38bdf8 !important;
}


/* Buttons */

.stButton>button {
    background-color: #2563eb;
    color: white;
    border-radius: 10px;
    border: none;
    padding: 10px 20px;
    font-weight: bold;
}

.stButton>button:hover {
    background-color: #1d4ed8;
    color: #facc15;
}


/* Text Input */

.stTextInput input {
    background-color: #f8fafc;
    color: black;
}


/* Text Area */

.stTextArea textarea {
    background-color: #f8fafc;
    color: black;
}


/* Success Message */

.stSuccess {
    background-color: #14532d;
    color: white;
}


/* Footer */

.footer {
    text-align: center;
    color: #cbd5e1;
    font-size: 15px;
    margin-top: 40px;
}

</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>

/* Hide Deploy Button */
[data-testid="stToolbar"] {
    visibility: hidden;
    height: 0%;
    position: fixed;
}

/* Hide Main Menu */
#MainMenu {
    visibility: hidden;
}

/* Hide Footer */
footer {
    visibility: hidden;
}

/* Hide Header */
header {
    visibility: hidden;
}

</style>
""", unsafe_allow_html=True)

# ------------------ Header Section ------------------

st.markdown(
    '<div class="sub-title">Intelligent Document Question Answering System using RAG and Large Language Models</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="brand-box">

<b>Author:</b> Ankita Dnyanoba Shinde <br><br>

<b>Date:</b> 09/05/2026<br><br>

<b>Technology:</b><br>
Python, Streamlit, PyPDF2, Sentence Transformers, FAISS, Ollama, Llama3<br><br>

<b>Tagline:</b><br>
Learn today, lead tomorrow.

</div>
""", unsafe_allow_html=True)

# ------------------ Sidebar Section ------------------

with st.sidebar:
    st.header(" > Project Information")

    st.write("""
    This project demonstrates a complete RAG-based PDF Question Answering System.
    """)

    st.subheader("Technologies Used")
    st.write("""
    - Python
    - Streamlit
    - PyPDF2
    - Sentence Transformers
    - FAISS
    - Ollama
    - Llama3
    """)

    st.subheader("Concepts Covered")
    st.write("""
    - PDF Processing
    - Text Chunking
    - Embeddings
    - Vector Database
    - Semantic Search
    - RAG
    - LLM
    - Prompt Engineering
    """)

    st.subheader("Ollama Command")
    st.code("ollama run llama3")


# ------------------ Main Application ------------------

tab1, tab2, tab3 = st.tabs([
    "Upload PDF",
    "Project Flow",
    "Technical Concepts"
])


with tab1:
    st.header("Upload PDF Document")

    uploaded_file = st.file_uploader(
        "Upload your PDF file here",
        type=["pdf"]
    )

    embedding_model = load_embedding_model()

    if uploaded_file is not None:

        st.success("PDF uploaded successfully!")

        with st.spinner("Extracting text from PDF..."):
            pdf_text = extract_text_from_pdf(uploaded_file)

        if pdf_text.strip() == "":
            st.error("No readable text found in the uploaded PDF.")
        else:
            st.subheader("Extracted Text Preview")

            st.text_area(
                "First 2000 characters from PDF",
                pdf_text[:2000],
                height=220
            )

            with st.spinner("Splitting text into chunks..."):
                chunks = split_text_into_chunks(pdf_text)

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric("Total Characters", len(pdf_text))

            with col2:
                st.metric("Total Chunks", len(chunks))

            with col3:
                st.metric("Chunk Size", "500 chars")

            with st.spinner("Creating embeddings and FAISS vector database..."):
                index, embeddings = create_vector_database(
                    chunks,
                    embedding_model
                )

            st.success("Vector database created successfully!")

            st.subheader("Ask Question from Uploaded PDF")

            question = st.text_input(
                "Enter your question"
            )

            if question:
                with st.spinner("Searching relevant content from PDF..."):
                    relevant_chunks = search_relevant_chunks(
                        question,
                        chunks,
                        index,
                        embedding_model,
                        top_k=3
                    )

                context = "\n\n".join(relevant_chunks)

                st.subheader("Retrieved Relevant Context")

                with st.expander("Click here to view retrieved context"):
                    st.write(context)

                with st.spinner("Generating answer using local LLM..."):
                    answer = ask_llm(question, context)

                st.subheader("Generated Answer")
                st.success(answer)


with tab2:
    st.header("RAG Architecture Flow")
    show_project_flow()


with tab3:
    st.header("Technical Concepts Used")

    st.markdown("""
    ### 1. PDF Processing
    PyPDF2 is used to extract text from PDF pages.

    ### 2. Text Chunking
    Large PDF text is divided into smaller overlapping chunks.

    ### 3. Embeddings
    Sentence Transformers convert text chunks into numerical vectors.

    ### 4. Vector Database
    FAISS stores embeddings and performs fast similarity search.

    ### 5. Semantic Search
    User question is converted into embedding and matched with PDF chunks.

    ### 6. RAG
    Retrieval Augmented Generation retrieves relevant context before generating answer.

    ### 7. LLM
    Llama3 running locally through Ollama generates final response.

    ### 8. Prompt Engineering
    Context and question are combined into a structured prompt.
    """)


# ------------------ Footer Section ------------------

st.markdown("""
<div class="footer">
<hr>
Project developed by Ankita Dnyanoba Shinde | Date: 09/05/2026
</div>
""", unsafe_allow_html=True)
